#!/bin/sh

npm i browserify-shim browsernizr cookieconsent fitvids jquery
npm i -D @babel/core \
  @babel/preset-env \
  @justeat/gulp-gh-pages \
  autoprefixer \
  babelify \
  browserify \
  cssnano \
  del \
  gulp \
  gulp-bro \
  gulp-copy \
  gulp-filter \
  gulp-if \
  gulp-postcss \
  gulp-processhtml \
  gulp-rev \
  gulp-rev-collector \
  gulp-rev-delete-original \
  gulp-rev-rewrite \
  gulp-sass \
  gulp-sourcemaps \
  gulp-uglify-es \
  gulp-watch \
  gulplog \
  lodash.assign \
  rev-del \
  uglifyify \
  vinyl-buffer \
  vinyl-paths \
  vinyl-source-stream

